# Generated by Django 4.1.7 on 2023-12-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0005_alter_match_options'),
        ('team', '0004_alter_team_cover_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fixture.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fixture.season')),
            ],
        ),
        migrations.CreateModel(
            name='StandingsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('matches_played', models.PositiveIntegerField()),
                ('matches_won', models.PositiveIntegerField()),
                ('matches_drawn', models.PositiveIntegerField()),
                ('matches_lost', models.PositiveIntegerField()),
                ('goals_for', models.PositiveIntegerField()),
                ('goals_against', models.PositiveIntegerField()),
                ('goal_difference', models.IntegerField()),
                ('points', models.IntegerField()),
                ('standings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings_teams', to='standings.standings')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings_teams', to='team.team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('standings', 'team')},
            },
        ),
    ]
