# Generated by Django 4.1.7 on 2024-01-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fixture.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fixture.season')),
            ],
        ),
        migrations.CreateModel(
            name='StandingsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('matches_won', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('matches_drawn', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('matches_lost', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('goals_for', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('goals_against', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('goal_difference', models.IntegerField(blank=True, default=0, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('standings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings_teams', to='standings.standings')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings_teams', to='team.team')),
            ],
            options={
                'ordering': ['points', 'goal_difference', 'goals_for', 'team__name'],
                'unique_together': {('standings', 'team')},
            },
        ),
    ]
