# Generated by Django 4.1.7 on 2023-12-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standingsteam',
            name='goal_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='goals_against',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='goals_for',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_drawn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_lost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_played',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_won',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
