# Generated by Django 4.1.7 on 2023-12-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_alter_standingsteam_goal_difference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standingsteam',
            options={'ordering': ['points', 'goal_difference', 'goals_for', 'team__name']},
        ),
        migrations.RemoveField(
            model_name='standingsteam',
            name='position',
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='goal_difference',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='goals_against',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='goals_for',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_drawn',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_lost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_played',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='matches_won',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standingsteam',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
