# Generated by Django 4.1.7 on 2024-01-10 19:13

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACL', 'Ashesi Champions League'), ('APL', 'Ashesi Premier League'), ('AFA Cup', 'Ashesi Football Association Cup'), ('Course Clash Cup', 'Course Clash Cup'), ('Inter-Class Cup', 'Inter-Class Cup'), ('Transfer', 'Transfer'), ('Injury', 'Injury'), ('Match Preview', 'Match Preview'), ('Match Report', 'Match Report'), ('Interview', 'Interview'), ('Opinion', 'Opinion'), ('Feature', 'Feature'), ('Tactical Analysis', 'Tactical Analysis'), ('Presser', 'Press Conference'), ('Other', 'Other'), ('Kasanoma', 'Kasanoma'), ('Northside', 'Northside'), ('Red Army', 'Red Army'), ('Legends United', 'Legends United'), ('Highlanders', 'Highlanders'), ('Elite', 'Elite')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(default=None, max_length=255)),
                ('title', models.TextField()),
                ('subtitle', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='news_items', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='news_items', to='news.newsitemtag')),
            ],
            options={
                'verbose_name_plural': 'news items',
                'ordering': ['-pub_date'],
            },
        ),
    ]
