# Generated by Django 4.1.7 on 2023-12-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsitemtag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitemtag',
            name='name',
            field=models.CharField(choices=[('ACL', 'Ashesi Champions League'), ('APL', 'Ashesi Premier League'), ('AFA Cup', 'Ashesi Football Association Cup'), ('Course Clash Cup', 'Course Clash Cup'), ('Inter-Class Cup', 'Inter-Class Cup'), ('Transfer', 'Transfer'), ('Injury', 'Injury'), ('Match Preview', 'Match Preview'), ('Match Report', 'Match Report'), ('Interview', 'Interview'), ('Opinion', 'Opinion'), ('Feature', 'Feature'), ('Tactical Analysis', 'Tactical Analysis'), ('Presser', 'Press Conference'), ('Other', 'Other')], max_length=200, unique=True),
        ),
    ]
