# Generated by Django 4.1.7 on 2024-01-07 16:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsitemtag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
        ),
    ]
