# Generated by Django 4.1.7 on 2023-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cover_photo_url',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
