# Generated by Django 4.1.7 on 2023-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_cover_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cover_photo_url',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
