# Generated by Django 4.1.7 on 2023-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='year_group',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
