# Generated by Django 4.1.7 on 2023-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Computer Engineering'), ('BA', 'Business Administration'), ('MIS', 'Management Information Systems')], default=None, max_length=150),
        ),
    ]
