# Generated by Django 4.1.7 on 2023-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
