# Generated by Django 4.1.7 on 2023-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.URLField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
