# Generated by Django 4.1.7 on 2023-12-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=1),
        ),
    ]
