# Generated by Django 4.1.7 on 2024-01-07 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_alter_coach_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
