# Generated by Django 4.1.7 on 2023-12-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('player', '0004_alter_player_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default=None, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away_team_score', models.IntegerField(blank=True, default=0, null=True)),
                ('match_time', models.TimeField()),
                ('has_started', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='away_matches', to='team.team')),
                ('competition', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.competition')),
                ('home_team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='home_matches', to='team.team')),
            ],
            options={
                'ordering': ['match_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Goal', 'Goal'), ('Yellow Card', 'Yellow Card'), ('Red Card', 'Red Card'), ('Substitution', 'Substitution')], default=None, max_length=50)),
                ('time', models.TimeField()),
                ('minute', models.IntegerField()),
                ('match', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to='fixture.match')),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to='player.player')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='substitution', to='fixture.matchevent')),
                ('player_in', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='substitutions_in', to='player.player')),
                ('player_out', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='substitutions_out', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('season', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='match_days', to='fixture.season')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='match_day',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.matchday'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.stage'),
        ),
        migrations.CreateModel(
            name='ManOfTheMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.match')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='players', to='player.player')),
            ],
            options={
                'ordering': ['match'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist_provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assists', to='player.player')),
                ('match_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='fixture.matchevent')),
                ('scoring_team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='scored_goals', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='StartingXI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_xis', to='fixture.match')),
                ('players', models.ManyToManyField(related_name='starting_xis', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'unique_together': {('match', 'team')},
            },
        ),
    ]
