# Generated by Django 4.1.7 on 2023-12-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('fixture', '0002_alter_competition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='away_matches', to='team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='home_matches', to='team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.matchday'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matches', to='fixture.referee'),
        ),
    ]
