# Generated by Django 4.1.7 on 2023-12-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_alter_match_away_team_alter_match_competition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='time',
        ),
    ]
