# Generated by Django 4.1.7 on 2023-12-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0004_remove_matchevent_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_day']},
        ),
    ]
